version: '3.4'

services:
  sentinel.testapp:
    image: ${DOCKER_REGISTRY-}sentineltestapp
    build:
      context: .
      dockerfile: Basic/Dockerfile

networks:
  default:
    external: true
    name: redis
