version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
     
    ports:
      - "2181:2181"
    networks:
      - kafkanet
  kafka:
      image: confluentinc/cp-kafka
      container_name: kafka
      environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      ports:
        - "9092:9092"
      networks:
        - kafkanet

networks:
  kafkanet: