version: '3.8'

services:
  redis-1:
    image: redis:6.2.6-alpine
    container_name: redis-1
    hostname: redis-1
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis
    volumes:
      - ./redis-1:/etc/redis/

  redis-2:
    image: redis:6.2.6-alpine
    container_name: redis-2
    hostname: redis-2
    depends_on:    
      - redis-1
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis
    volumes:
      - ./redis-2:/etc/redis/

  redis-3:
    image: redis:6.2.6-alpine
    container_name: redis-3
    hostname: redis-3
    depends_on:    
      - redis-1
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis
    volumes:
      - ./redis-3:/etc/redis/

  sentinel-1:
    image: redis:6.2.6-alpine
    container_name: sentinel-1
    hostname: sentinel-1
    depends_on:    
      - redis-1
      - redis-2
      - redis-3
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis
    volumes:
      - ./sentinel-1:/etc/redis/ 

  sentinel-2:
    image: redis:6.2.6-alpine
    container_name: sentinel-2
    hostname: sentinel-2
    depends_on:    
      - sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis
    volumes:
      - ./sentinel-2:/etc/redis/ 

  sentinel-3:
    image: redis:6.2.6-alpine
    container_name: sentinel-3
    hostname: sentinel-3
    depends_on:    
      - sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis
    volumes:
      - ./sentinel-3:/etc/redis/ 

networks:
  redis:
    name: redis